---
- name: Create container directories
  file:
    dest: '{{ item }}'
    state: directory
    owner: dockremap
    group: docker
    mode: 0775
  with_items:
    - '{{ logos_node_cont_vol }}'
    - '{{ logos_node_conf_path }}'

- name: Create waku config file
  register: logos_node_config
  template:
    src: waku_config.json.j2
    dest: '{{ logos_node_conf_path }}/waku_config.json'
    owner: dockremap
    group: docker
    mode: 0644

- name: Create entrypoint script
  register: logos_node_entrypoint
  template:
    src: entrypoint.sh.j2
    dest: '{{ logos_node_cont_vol }}/entrypoint.sh'
    owner: dockremap
    group: docker
    mode: 0755