---
- name: Set config changed fact
  set_fact:
    logos_node_config_changed: >-
      {{ (logos_node_delivery_config.changed | default(false))
      or (logos_node_storage_config.changed | default(false))
      or (logos_node_blockchain_config.changed | default(false))
      or (logos_node_entrypoint.changed | default(false)) }}

- name: Create compose file
  template:
    src: docker-compose.yml.j2
    dest: '{{ logos_node_cont_vol }}/docker-compose.yml'
    owner: dockremap
    group: docker
    mode: 0664

- name: Create container
  community.docker.docker_compose_v2:
    project_src: '{{ logos_node_cont_vol }}'
    recreate: '{{ "always" if (logos_node_config_changed | default(false) | bool) else compose_recreate }}'
    pull: '{{ compose_pull }}'
    state: '{{ compose_state }}'
    wait: true
    wait_timeout: 180
  register: logos_node_container