---
- import_tasks: config.yml

- include_tasks: '{{ module }}/config.yml'
  when: lookup('vars', 'logos_node_' + module + '_enabled') | bool
  loop: ['delivery', 'storage', 'blockchain']
  loop_control:
    loop_var: module

- import_tasks: docker.yml

- include_tasks: '{{ module }}/query.yml'
  when: lookup('vars', 'logos_node_' + module + '_enabled') | bool
  loop: ['delivery', 'storage', 'blockchain']
  loop_control:
    loop_var: module

- name: Gather container info
  docker_container_info:
    name: '{{ logos_node_cont_name }}'
  register: logos_node_cont

- include_tasks: '{{ module }}/consul.yml'
  when: lookup('vars', 'logos_node_' + module + '_enabled') | bool
  loop: ['delivery', 'storage', 'blockchain']
  loop_control:
    loop_var: module

- import_tasks: monitor.yml
  when: logos_node_monitor_enabled